# Generated by Django 4.1 on 2023-02-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gesture',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
