# Generated by Django 4.1 on 2022-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='appuser',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='appuser',
            name='surname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
