# Generated by Django 4.1 on 2022-08-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0002_appuser_email_appuser_name_appuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='read',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.read'),
        ),
    ]
