# Generated by Django 4.1 on 2022-08-23 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BodyLanguage', '0003_alter_emotion_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behaviour',
            name='read',
        ),
        migrations.RemoveField(
            model_name='bodypartgesture',
            name='read',
        ),
        migrations.RemoveField(
            model_name='contextgesture',
            name='read',
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='read',
        ),
        migrations.AddField(
            model_name='read',
            name='behaviour',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.behaviour'),
        ),
        migrations.AddField(
            model_name='read',
            name='body_part_gesture',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.bodypartgesture'),
        ),
        migrations.AddField(
            model_name='read',
            name='context_gesture',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.contextgesture'),
        ),
        migrations.AddField(
            model_name='read',
            name='emotion',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.emotion'),
        ),
        migrations.AlterField(
            model_name='read',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
