# Generated by Django 4.1 on 2022-08-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0004_remove_behaviour_read_remove_bodypartgesture_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviour',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bodypartgesture',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contextgesture',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emotion',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Read',
        ),
    ]
