# Generated by Django 4.1 on 2022-08-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0005_behaviour_read_bodypartgesture_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(max_length=50)),
                ('male', models.BooleanField()),
                ('female', models.BooleanField()),
                ('adult', models.BooleanField()),
                ('child', models.BooleanField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
        migrations.AlterField(
            model_name='bodypartgesture',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.feeling'),
        ),
    ]
