# Generated by Django 4.1 on 2022-08-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0007_rename_feeling_emotion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emotion',
            new_name='Feeling',
        ),
        migrations.RenameField(
            model_name='feeling',
            old_name='emotion',
            new_name='feeling',
        ),
    ]
