# Generated by Django 4.1 on 2022-08-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0008_rename_emotion_feeling_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeling',
        ),
    ]
