# Generated by Django 4.1 on 2022-08-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0009_delete_feeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bodypartgesture',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.meaning'),
        ),
    ]
