# Generated by Django 4.1 on 2022-08-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0010_meaning_alter_bodypartgesture_feeling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypartgesture',
            name='feeling',
        ),
        migrations.CreateModel(
            name='MeaningGesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.bodypartgesture')),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.meaning')),
            ],
        ),
    ]
