# Generated by Django 4.1 on 2022-08-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0011_remove_bodypartgesture_feeling_meaninggesture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypartgesture',
            name='feeling',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.meaning'),
        ),
        migrations.DeleteModel(
            name='MeaningGesture',
        ),
    ]
