# Generated by Django 4.1 on 2022-08-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0012_bodypartgesture_feeling_delete_meaninggesture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypartgesture',
            name='feeling',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.meaning'),
        ),
    ]
