# Generated by Django 4.1 on 2022-08-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0013_alter_bodypartgesture_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='meaning',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
