# Generated by Django 4.1 on 2022-08-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BodyLanguage', '0015_remove_bodypartgesture_feeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypartgesture',
            name='feeling',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BodyLanguage.meaning'),
        ),
    ]
